=== StoryAnvil/SkinEditor/src/schema/stAccessory.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "$id": "storyAnvilAccessory",
    "$anchor": "StoryAnvil",
    "type": "object",
    "properties": {
        "meta": {
            "description": "Metadata for this accessory. This settings do not affect how accessory is rendered",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Display name for this accessory",
                    "type": "string"
                },
                "author": {
                    "description": "Author of authors of this accessory",
                    "type": "string"
                },
                "category": {
                    "description": "Category of this accessory",
                    "type": "string",
                    "enum": [
                        "hat",
                        "face",
                        "hair",
                        "body",
                        "arms",
                        "legs",
                        "feet"
                    ]
                },
                "tags": {
                    "description": "Any tags for this accessory. For example \"christmas\" for christmas-themed accessories",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "uniqueItems": true,
                    "maxItems": 10
                }
            },
            "required": ["name", "author", "category", "tags"]
        },
        "inputs": {
            "description": "Inputs this accessory takes to customize its apearance.",
            "type": "object",
            "additionalProperties": {
                "oneOf": [
                    {
                        "description": "Color input",
                        "type": "object",
                        "properties": {
                            "type": {
                                "description": "Type of this input",
                                "type": "string",
                                "enum": ["color"]
                            },
                            "name": {
                                "description": "Display name for this input",
                                "type": "string"
                            },
                            "default": {
                                "description": "Hex code of color to use as default value for this input. Alpha channel is not currently supported",
                                "type": "string",
                                "pattern": "^[0-9ABCDEF]{6}$"
                            },
                            "alpha": {
                                "description": "Alpha value",
                                "$ref": "#/definitions/value",
                                "default": 255
                            }
                        },
                        "required": ["type", "name", "default"]
                    },
                    {
                        "description": "Contant input",
                        "type": "object",
                        "properties": {
                            "type": {
                                "description": "Type of this input",
                                "type": "string",
                                "enum": ["constant", "const"]
                            },
                            "value": {
                                "$ref": "#/definitions/value"
                            }
                        },
                        "required": ["type", "value"]
                    },
                    {
                        "description": "Slim or classic input. Returns true if current skin is slim",
                        "type": "object",
                        "properties": {
                            "type": {
                                "description": "Type of this input",
                                "type": "string",
                                "enum": ["isSlim"]
                            }
                        },
                        "required": ["type"]
                    },
                    {
                        "description": "Input that returns true",
                        "type": "object",
                        "properties": {
                            "type": {
                                "description": "Type of this input",
                                "type": "string",
                                "enum": ["always"]
                            }
                        },
                        "required": ["type"]
                    },
                    {
                        "description": "Integer range input",
                        "type": "object",
                        "properties": {
                            "type": {
                                "description": "Type of this input",
                                "type": "string",
                                "enum": ["intrange"]
                            },
                            "name": {
                                "description": "Display name for this input",
                                "type": "string"
                            },
                            "default": {
                                "description": "Default value for this input. If not specified minimum value is used",
                                "type": "integer"
                            },
                            "minimum": {
                                "description": "Minimum value for this input",
                                "type": "integer"
                            },
                            "maximum": {
                                "description": "Maximum value for this input",
                                "type": "integer"
                            }
                        },
                        "required": ["type", "name", "minimum", "maximum"]
                    }
                ]
            }
        },
        "actions": {
            "description": "List of actions to apply",
            "$ref": "#/definitions/actions"
        },
        "layers": {
            "description": "Layers to compose accessory's texture from",
            "type": "object",
            "additionalProperties": {
                "description": "Single accessory layer",
                "type": "object",
                "properties": {
                    "buffer": {
                        "description": "ID of existing pixel buffer to use for this layer. Pixel buffer must be declared in accessory's buffers object",
                        "type": "string"
                    },
                    "offset": {
                        "description": "Coordinate offset for this layer (in pixels)",
                        "type": "array",
                        "items": [
                            {
                                "description": "X offset",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 64
                            },
                            {
                                "description": "Y offset",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 64
                            }
                        ],
                        "additionalItems": false,
                        "minItems": 2,
                        "default": [0, 0]
                    },
                    "enabledByDefault": {
                        "description": "True of this layer should be enabled by default",
                        "type": "boolean",
                        "default": false
                    }
                },
                "required": ["buffer"]
            }
        },
        "buffers": {
            "description": "Pixel buffers used to draw layers",
            "type": "object",
            "additionalProperties": {
                "description": "Single pixel buffer",
                "type": "object",
                "properties": {
                    "px": {
                        "description": "Pixel data for this buffer",
                        "type": "object",
                        "patternProperties": {
                            "^[0-9ABCDEF]{6}|[0-9ABCDEF]{8}$": {
                                "$ref": "#/definitions/pixelPosArray"
                            },
                            "^#": {
                                "description": "Use color from input with ID specified after #",
                                "$ref": "#/definitions/pixelPosArray"
                            }
                        },
                        "additionalProperties": false
                    }
                },
                "required": ["px"]
            },
            "minProperties": 1
        }
    },
    "required": ["meta", "layers", "buffers"],
    "definitions": {
        "pixelPosArray": {
            "description": "Pixels of single color",
            "type": "array",
            "items": {
                "description": "Sum of Y-coordinate multiplied by 100 and X-coordinate",
                "minimum": 0
            },
            "minItems": 1
        },
        "actions": {
            "description": "List of actions this input causes",
            "type": "array",
            "items": [
                {
                    "oneOf": [
                        {
                            "description": "Enable/Disable layers",
                            "type": "object",
                            "properties": {
                                "type": {
                                    "description": "Type of this action",
                                    "type": "string",
                                    "enum": ["setlayer"]
                                },
                                "enable": {
                                    "description": "List of layers to enable",
                                    "type": "array",
                                    "items": {
                                        "description": "Name of layer to enable",
                                        "type": "string"
                                    },
                                    "default": []
                                },
                                "disable": {
                                    "description": "List of layers to disable",
                                    "type": "array",
                                    "items": {
                                        "description": "Name of layer to disable",
                                        "type": "string"
                                    },
                                    "default": []
                                }
                            },
                            "required": ["type"]
                        },
                        {
                            "description": "Set layers offset",
                            "type": "object",
                            "properties": {
                                "type": {
                                    "description": "Type of this action",
                                    "type": "string",
                                    "enum": ["addoffset"]
                                },
                                "layers": {
                                    "description": "ID of layers to add offset for",
                                    "type": "array",
                                    "items": {
                                        "description": "Single layer ID",
                                        "type": "string"
                                    }
                                },
                                "x_offset": {
                                    "description": "X Offset value",
                                    "$ref": "#/definitions/value"
                                },
                                "y_offset": {
                                    "description": "Y Offset value",
                                    "$ref": "#/definitions/value"
                                }
                            },
                            "required": ["type", "layers"]
                        },
                        {
                            "description": "Set layers tint",
                            "type": "object",
                            "properties": {
                                "type": {
                                    "description": "Type of this action",
                                    "type": "string",
                                    "enum": ["settint"]
                                },
                                "layers": {
                                    "description": "ID of layers to set tint for",
                                    "type": "array",
                                    "items": {
                                        "description": "Single layer ID",
                                        "type": "string"
                                    }
                                },
                                "tint": {
                                    "description": "Tint color (HEX)",
                                    "$ref": "#/definitions/value"
                                }
                            },
                            "required": ["type", "layers"]
                        },
                        {
                            "description": "Execute if",
                            "type": "object",
                            "properties": {
                                "type": {
                                    "description": "Type of this action",
                                    "type": "string",
                                    "enum": ["if"]
                                },
                                "condition": {
                                    "description": "Condition for this if",
                                    "type": "array",
                                    "items": [
                                        {
                                            "$ref": "#/definitions/value"
                                        },
                                        {
                                            "description": "Operator for values",
                                            "type": "string",
                                            "enum": [
                                                "==",
                                                "!=",
                                                ">",
                                                "<",
                                                ">=",
                                                "<="
                                            ]
                                        },
                                        {
                                            "$ref": "#/definitions/value"
                                        }
                                    ]
                                },
                                "actions": {
                                    "description": "Actions to execute if condition resulted in positive value",
                                    "$ref": "#/definitions/actions"
                                }
                            },
                            "required": ["type", "condition", "actions"]
                        },
                        {
                            "description": "Execute if boolean value",
                            "type": "object",
                            "properties": {
                                "type": {
                                    "description": "Type of this action",
                                    "type": "string",
                                    "enum": ["ifBool"]
                                },
                                "condition": {
                                    "$ref": "#/definitions/value"
                                },
                                "if": {
                                    "description": "Actions to execute if condition is true",
                                    "$ref": "#/definitions/actions"
                                },
                                "else": {
                                    "description": "Actions to execute if condition is false",
                                    "$ref": "#/definitions/actions"
                                }
                            },
                            "required": ["type", "condition"]
                        }
                    ]
                }
            ]
        },
        "value": {
            "oneOf": [
                {"description": "Literal Value", "type": "boolean"},
                {"description": "Literal Value", "type": "number"},
                {"description": "Literal Value", "type": "string"},
                {
                    "description": "Expression Value (get input value)",
                    "type": "object",
                    "properties": {
                        "type": {
                            "description": "Expression type",
                            "enum": ["input"]
                        },
                        "input": {
                            "description": "ID of input to take value from",
                            "type": "string"
                        }
                    },
                    "required": ["type", "input"]
                }
            ]
        }
    }
}

=== StoryAnvil/SkinEditor/src/accessories/tshirt.json
{
    "$schema": "../schema/stAccessory.json",
    "meta": {
        "name": "Blank T-Shirt",
        "author": "BloodRain121",
        "category": "body",
        "tags": []
    },
    "inputs": {
        "tint0": {
            "type": "color",
            "default": "FFFFFF",
            "name": "Color"
        }
    },
    "actions": [
        {
            "type": "settint",
            "tint": {
                "type": "input",
                "input": "tint0"
            },
            "layers": ["l0"]
        }
    ],
    "layers": {
        "l0": {
            "buffer": "b0",
            "enabledByDefault": true
        }
    },
    "buffers": {
        "b0": {
            "px": {
                "B5D8E9": [
                    2016, 2116, 2616, 2716, 2816, 2017, 2917, 3017, 2018, 3018,
                    2019, 2719, 2819, 2919, 1620, 1720, 1820, 1920, 2020, 2720,
                    2820, 2920, 1621, 1721, 1821, 1921, 2921, 3021, 1622, 2022,
                    3022, 3122, 1623, 2123, 3023, 3123, 1624, 2124, 3024, 3124,
                    1625, 2025, 2925, 3025, 1626, 1726, 1826, 1926, 2826, 2926,
                    3026, 1627, 1727, 1827, 1927, 2027, 2627, 2727, 2827, 2927,
                    2028, 2628, 2728, 2828, 2928, 2029, 2929, 3029, 2030, 2930,
                    3030, 2031, 2131, 2731, 2831, 2931, 2032, 2132, 2732, 2832,
                    2932, 5232, 5332, 5432, 2033, 2933, 3033, 5233, 3034, 5234,
                    3035, 3135, 5235, 5335, 5435, 3036, 3136, 5336, 5436, 2937,
                    3037, 3137, 2038, 2838, 2938, 3038, 5538, 2039, 2139, 2639,
                    2739, 2839, 2345, 3945, 5545, 2147, 2247, 5347, 5447, 2048,
                    2148, 2248, 2049, 2050, 2051, 2151, 2251, 2152, 2252, 2354,
                    3954, 5554, 5561
                ],
                "D0E8F1": [
                    2216, 2416, 2516, 2117, 2717, 2817, 2918, 2119, 2519, 2619,
                    2120, 2520, 2620, 2021, 2621, 2721, 2821, 2722, 2822, 2922,
                    2823, 2923, 2724, 2824, 2924, 2725, 2825, 2026, 2126, 2626,
                    2726, 2127, 2227, 2427, 2527, 2128, 2228, 2428, 2528, 2129,
                    2829, 2730, 2830, 2231, 2531, 2631, 2232, 2532, 2632, 2133,
                    2733, 2833, 2034, 2834, 2934, 2035, 2935, 2036, 2836, 2936,
                    4836, 4936, 5036, 5136, 5236, 2037, 2737, 2837, 5437, 2138,
                    2638, 2738, 2239, 2439, 2539, 5539, 2340, 3940, 5540, 2343,
                    3943, 5543, 2344, 3944, 5544, 2246, 5446, 1647, 1747, 1847,
                    1947, 2047, 5247, 2052, 2253, 2355, 3955, 5555, 5556, 5559,
                    5560
                ],
                "DDEFF4": [
                    2316, 2217, 2317, 2417, 2517, 2617, 2118, 2218, 2318, 2418,
                    2518, 2618, 2718, 2818, 2219, 2319, 2419, 2220, 2320, 2420,
                    2121, 2221, 2321, 2421, 2521, 2122, 2222, 2322, 2422, 2522,
                    2622, 2223, 2323, 2423, 2523, 2623, 2723, 2224, 2324, 2424,
                    2524, 2624, 2125, 2225, 2325, 2425, 2525, 2625, 2226, 2326,
                    2426, 2526, 2327, 2328, 2229, 2329, 2429, 2529, 2629, 2729,
                    2130, 2230, 2330, 2430, 2530, 2630, 2331, 2431, 2332, 2432,
                    2233, 2333, 2433, 2533, 2633, 2134, 2234, 2334, 2434, 2534,
                    2634, 2734, 2135, 2235, 2335, 2435, 2535, 2635, 2735, 2835,
                    2136, 2236, 2336, 2436, 2536, 2636, 2736, 2137, 2237, 2337,
                    2437, 2537, 2637, 4837, 4937, 5037, 5137, 5237, 5337, 2238,
                    2338, 2438, 2538, 4838, 4938, 5038, 5138, 5238, 5338, 5438,
                    2339, 4839, 4939, 5039, 5139, 5239, 5339, 5439, 2040, 2140,
                    2240, 5240, 5340, 5440, 2041, 2141, 2241, 2341, 3941, 5241,
                    5341, 5441, 5541, 2042, 2142, 2242, 2342, 3942, 5242, 5342,
                    5442, 5542, 2043, 2143, 2243, 5243, 5343, 5443, 1644, 1744,
                    1844, 1944, 2044, 2144, 2244, 5244, 5344, 5444, 1645, 1745,
                    1845, 1945, 2045, 2145, 2245, 5245, 5345, 5445, 1646, 1746,
                    1846, 1946, 2046, 2146, 5246, 5346, 2053, 2153, 2054, 2154,
                    2254, 2055, 2155, 2255, 5557, 5558
                ],
                "9CC7E4": [
                    2916, 3016, 3116, 3117, 3118, 3019, 3119, 3020, 3120, 3121,
                    3125, 3126, 3027, 3127, 3028, 3128, 3129, 3130, 3031, 3131,
                    3032, 3132, 5532, 3133, 5333, 5433, 5533, 3134, 5334, 5434,
                    5534, 5535, 5536, 5537, 3138, 2939, 3039, 3139, 2346, 3946,
                    5546, 2347, 3947, 5547, 2348, 3948, 5548, 2149, 2249, 2349,
                    3949, 5549, 2150, 2250, 2350, 3950, 5550, 2351, 3951, 5551,
                    2352, 3952, 5552, 2353, 3953, 5553, 5562, 5563
                ],
                "00000000": [
                    3640, 3740, 3840, 3641, 3741, 3841, 3642, 3742, 3842, 3643,
                    3743, 3843, 3244, 3344, 3444, 3544, 3644, 3744, 3844, 3245,
                    3345, 3445, 3545, 3645, 3745, 3845, 3246, 3346, 3446, 3546,
                    3646, 3746, 3846, 3247, 3347, 3447, 3547, 3647, 3747, 3847,
                    3648, 3748, 3848, 5248, 5348, 5448, 3649, 3749, 3849, 5249,
                    5349, 5449, 3650, 3750, 3850, 5250, 5350, 5450, 3651, 3751,
                    3851, 5251, 5351, 5451, 3652, 3752, 3852, 4852, 4952, 5052,
                    5152, 5352, 5452, 3653, 3753, 3853, 4853, 4953, 5053, 5153,
                    5253, 5353, 5453, 3654, 3754, 3854, 4854, 4954, 5054, 5154,
                    5254, 5354, 5454, 3655, 3755, 3855, 4855, 4955, 5055, 5155,
                    5255, 5355, 5455, 5256, 5356, 5456, 5257, 5357, 5457, 5258,
                    5358, 5458, 5259, 5359, 5459, 5260, 5360, 5460, 5261, 5361,
                    5461, 5262, 5362, 5462, 5263, 5363, 5463
                ]
            }
        }
    }
}
