=== StoryAnvil/SkinEditor/src/schema/stAccessory.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "$id": "storyAnvilAccessory",
    "$anchor": "StoryAnvil",
    "type": "object",
    "properties": {
        "meta": {
            "description": "Metadata for this accessory. This settings do not affect how accessory is rendered",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Display name for this accessory",
                    "type": "string"
                },
                "author": {
                    "description": "Author of authors of this accessory",
                    "type": "string"
                },
                "category": {
                    "description": "Category of this accessory",
                    "type": "string",
                    "enum": [
                        "hat",
                        "face",
                        "hair",
                        "body",
                        "arms",
                        "legs",
                        "feet"
                    ]
                },
                "tags": {
                    "description": "Any tags for this accessory. For example \"christmas\" for christmas-themed accessories",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "uniqueItems": true,
                    "maxItems": 10
                }
            },
            "required": ["name", "author", "category", "tags"]
        },
        "inputs": {
            "description": "Inputs this accessory takes to customize its apearance.",
            "type": "object",
            "additionalProperties": {
                "oneOf": [
                    {
                        "description": "Color input",
                        "type": "object",
                        "properties": {
                            "type": {
                                "description": "Type of this input",
                                "type": "string",
                                "enum": ["color"]
                            },
                            "name": {
                                "description": "Display name for this input",
                                "type": "string"
                            },
                            "default": {
                                "description": "Hex code of color to use as default value for this input. Alpha channel is not currently supported",
                                "type": "string",
                                "pattern": "^[0-9ABCDEF]{6}$"
                            },
                            "alpha": {
                                "description": "Alpha value",
                                "$ref": "#/definitions/value",
                                "default": 255
                            }
                        },
                        "required": ["type", "name", "default"]
                    },
                    {
                        "description": "Contant input",
                        "type": "object",
                        "properties": {
                            "type": {
                                "description": "Type of this input",
                                "type": "string",
                                "enum": ["constant", "const"]
                            },
                            "value": {
                                "$ref": "#/definitions/value"
                            }
                        },
                        "required": ["type", "value"]
                    },
                    {
                        "description": "Slim or classic input. Returns true if current skin is slim",
                        "type": "object",
                        "properties": {
                            "type": {
                                "description": "Type of this input",
                                "type": "string",
                                "enum": ["isSlim"]
                            }
                        },
                        "required": ["type"]
                    },
                    {
                        "description": "Input that returns true",
                        "type": "object",
                        "properties": {
                            "type": {
                                "description": "Type of this input",
                                "type": "string",
                                "enum": ["always"]
                            }
                        },
                        "required": ["type"]
                    },
                    {
                        "description": "Integer range input",
                        "type": "object",
                        "properties": {
                            "type": {
                                "description": "Type of this input",
                                "type": "string",
                                "enum": ["intrange"]
                            },
                            "name": {
                                "description": "Display name for this input",
                                "type": "string"
                            },
                            "default": {
                                "description": "Default value for this input. If not specified minimum value is used",
                                "type": "integer"
                            },
                            "minimum": {
                                "description": "Minimum value for this input",
                                "type": "integer"
                            },
                            "maximum": {
                                "description": "Maximum value for this input",
                                "type": "integer"
                            }
                        },
                        "required": ["type", "name", "minimum", "maximum"]
                    }
                ]
            }
        },
        "actions": {
            "description": "List of actions to apply",
            "$ref": "#/definitions/actions"
        },
        "layers": {
            "description": "Layers to compose accessory's texture from",
            "type": "object",
            "additionalProperties": {
                "description": "Single accessory layer",
                "type": "object",
                "properties": {
                    "buffer": {
                        "description": "ID of existing pixel buffer to use for this layer. Pixel buffer must be declared in accessory's buffers object",
                        "type": "string"
                    },
                    "offset": {
                        "description": "Coordinate offset for this layer (in pixels)",
                        "type": "array",
                        "items": [
                            {
                                "description": "X offset",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 64
                            },
                            {
                                "description": "Y offset",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 64
                            }
                        ],
                        "additionalItems": false,
                        "minItems": 2,
                        "default": [0, 0]
                    },
                    "enabledByDefault": {
                        "description": "True of this layer should be enabled by default",
                        "type": "boolean",
                        "default": false
                    }
                },
                "required": ["buffer"]
            }
        },
        "buffers": {
            "description": "Pixel buffers used to draw layers",
            "type": "object",
            "additionalProperties": {
                "description": "Single pixel buffer",
                "type": "object",
                "properties": {
                    "px": {
                        "description": "Pixel data for this buffer",
                        "type": "object",
                        "patternProperties": {
                            "^[0-9ABCDEF]{6}|[0-9ABCDEF]{8}$": {
                                "$ref": "#/definitions/pixelPosArray"
                            },
                            "^#": {
                                "description": "Use color from input with ID specified after #",
                                "$ref": "#/definitions/pixelPosArray"
                            }
                        },
                        "additionalProperties": false
                    }
                },
                "required": ["px"]
            },
            "minProperties": 1
        }
    },
    "required": ["meta", "layers", "buffers"],
    "definitions": {
        "pixelPosArray": {
            "description": "Pixels of single color",
            "type": "array",
            "items": {
                "description": "Sum of Y-coordinate multiplied by 100 and X-coordinate",
                "minimum": 0
            },
            "minItems": 1
        },
        "actions": {
            "description": "List of actions this input causes",
            "type": "array",
            "items": [
                {
                    "oneOf": [
                        {
                            "description": "Enable/Disable layers",
                            "type": "object",
                            "properties": {
                                "type": {
                                    "description": "Type of this action",
                                    "type": "string",
                                    "enum": ["setlayer"]
                                },
                                "enable": {
                                    "description": "List of layers to enable",
                                    "type": "array",
                                    "items": {
                                        "description": "Name of layer to enable",
                                        "type": "string"
                                    },
                                    "default": []
                                },
                                "disable": {
                                    "description": "List of layers to disable",
                                    "type": "array",
                                    "items": {
                                        "description": "Name of layer to disable",
                                        "type": "string"
                                    },
                                    "default": []
                                }
                            },
                            "required": ["type"]
                        },
                        {
                            "description": "Set layers offset",
                            "type": "object",
                            "properties": {
                                "type": {
                                    "description": "Type of this action",
                                    "type": "string",
                                    "enum": ["addoffset"]
                                },
                                "layers": {
                                    "description": "ID of layers to add offset for",
                                    "type": "array",
                                    "items": {
                                        "description": "Single layer ID",
                                        "type": "string"
                                    }
                                },
                                "x_offset": {
                                    "description": "X Offset value",
                                    "$ref": "#/definitions/value"
                                },
                                "y_offset": {
                                    "description": "Y Offset value",
                                    "$ref": "#/definitions/value"
                                }
                            },
                            "required": ["type", "layers"]
                        },
                        {
                            "description": "Set layers tint",
                            "type": "object",
                            "properties": {
                                "type": {
                                    "description": "Type of this action",
                                    "type": "string",
                                    "enum": ["settint"]
                                },
                                "layers": {
                                    "description": "ID of layers to set tint for",
                                    "type": "array",
                                    "items": {
                                        "description": "Single layer ID",
                                        "type": "string"
                                    }
                                },
                                "tint": {
                                    "description": "Tint color (HEX)",
                                    "$ref": "#/definitions/value"
                                }
                            },
                            "required": ["type", "layers"]
                        },
                        {
                            "description": "Execute if",
                            "type": "object",
                            "properties": {
                                "type": {
                                    "description": "Type of this action",
                                    "type": "string",
                                    "enum": ["if"]
                                },
                                "condition": {
                                    "description": "Condition for this if",
                                    "type": "array",
                                    "items": [
                                        {
                                            "$ref": "#/definitions/value"
                                        },
                                        {
                                            "description": "Operator for values",
                                            "type": "string",
                                            "enum": [
                                                "==",
                                                "!=",
                                                ">",
                                                "<",
                                                ">=",
                                                "<="
                                            ]
                                        },
                                        {
                                            "$ref": "#/definitions/value"
                                        }
                                    ]
                                },
                                "actions": {
                                    "description": "Actions to execute if condition resulted in positive value",
                                    "$ref": "#/definitions/actions"
                                }
                            },
                            "required": ["type", "condition", "actions"]
                        },
                        {
                            "description": "Execute if boolean value",
                            "type": "object",
                            "properties": {
                                "type": {
                                    "description": "Type of this action",
                                    "type": "string",
                                    "enum": ["ifBool"]
                                },
                                "condition": {
                                    "$ref": "#/definitions/value"
                                },
                                "if": {
                                    "description": "Actions to execute if condition is true",
                                    "$ref": "#/definitions/actions"
                                },
                                "else": {
                                    "description": "Actions to execute if condition is false",
                                    "$ref": "#/definitions/actions"
                                }
                            },
                            "required": ["type", "condition"]
                        }
                    ]
                }
            ]
        },
        "value": {
            "oneOf": [
                {"description": "Literal Value", "type": "boolean"},
                {"description": "Literal Value", "type": "number"},
                {"description": "Literal Value", "type": "string"},
                {
                    "description": "Expression Value (get input value)",
                    "type": "object",
                    "properties": {
                        "type": {
                            "description": "Expression type",
                            "enum": ["input"]
                        },
                        "input": {
                            "description": "ID of input to take value from",
                            "type": "string"
                        }
                    },
                    "required": ["type", "input"]
                }
            ]
        }
    }
}

=== StoryAnvil/SkinEditor/src/accessories/pants.json
{
    "$schema": "../schema/stAccessory.json",
    "meta": {
        "name": "Pants",
        "author": "BloodRain121",
        "category": "legs",
        "tags": []
    },
    "inputs": {
        "tint0": {
            "type": "color",
            "default": "FFFFFF",
            "name": "Color"
        }
    },
    "actions": [
        {
            "type": "settint",
            "tint": {
                "type": "input",
                "input": "tint0"
            },
            "layers": ["l0"]
        }
    ],
    "layers": {
        "l0": {
            "buffer": "b0",
            "enabledByDefault": true
        }
    },
    "buffers": {
        "b0": {
            "px": {
                "302872": [
                    5801, 5901, 5802, 5902, 2506, 2507, 2508, 2109, 2209, 2309,
                    2409, 2509, 2609, 2709, 4209, 4309, 2110, 2210, 2310, 2410,
                    2510, 2610, 2710, 4210, 4310, 2511, 2512, 2513, 5716, 5317,
                    5417, 5517, 5617, 5717, 5817, 5917, 5318, 5418, 5518, 5618,
                    5718, 5818, 5918, 5719, 5720, 5721, 5730, 5731
                ],
                "352118": [3122, 3125, 3134, 3137],
                "463AA5": [
                    2000, 2400, 2600, 2800, 4200, 4400, 2501, 2502, 2003, 2403,
                    2603, 2803, 4203, 4403, 1604, 1704, 1804, 1904, 2004, 2404,
                    2604, 2804, 4204, 4404, 2105, 2205, 2305, 2705, 4305, 5906,
                    5807, 6007, 5808, 6008, 5811, 6011, 5812, 6012, 5913, 2114,
                    2214, 2314, 2714, 4314, 2015, 2415, 2615, 2815, 4215, 4415,
                    5322, 5422, 5522, 5922, 4823, 4923, 5023, 5123, 5223, 5623,
                    5823, 6023, 5224, 5624, 5824, 6024, 5725, 5726, 5227, 5627,
                    5827, 6027, 5228, 5628, 5828, 6028, 5329, 5429, 5529, 5929
                ],
                "4A3DAD": [
                    2100, 2200, 2300, 2700, 4300, 2001, 2401, 2601, 2801, 4201,
                    4401, 2002, 2402, 2602, 2802, 4202, 4402, 2103, 2203, 2303,
                    2703, 4303, 2104, 2204, 2304, 2704, 4304, 5907, 5908, 5809,
                    6009, 5810, 6010, 5911, 5912, 2115, 2215, 2315, 2715, 4315,
                    5323, 5423, 5523, 5923, 5324, 5424, 5524, 5924, 5225, 5625,
                    5825, 6025, 5226, 5626, 5826, 6026, 5327, 5427, 5527, 5927,
                    5328, 5428, 5528, 5928
                ],
                "382F85": [
                    2500, 5800, 5900, 6000, 6001, 6002, 2503, 5803, 5903, 6003,
                    2504, 5804, 5904, 6004, 2505, 1607, 1707, 1807, 1907, 2007,
                    2107, 2207, 2307, 2407, 2607, 2707, 2807, 4207, 4307, 4407,
                    2008, 2108, 2208, 2308, 2408, 2608, 2708, 2808, 4208, 4308,
                    4408, 2009, 2809, 4409, 2010, 2810, 4410, 2011, 2111, 2211,
                    2311, 2411, 2611, 2711, 2811, 4211, 4311, 4411, 2012, 2112,
                    2212, 2312, 2412, 2612, 2712, 2812, 4212, 4312, 4412, 2514,
                    2515, 5815, 5915, 6015, 5216, 5316, 5416, 5516, 5616, 5816,
                    5916, 6016, 5217, 6017, 5218, 6018, 5219, 5319, 5419, 5519,
                    5619, 5819, 5919, 6019, 4820, 4920, 5020, 5120, 5220, 5320,
                    5420, 5520, 5620, 5820, 5920, 6020, 5722, 5723, 5724, 5727,
                    5728, 5729, 5231, 5331, 5431, 5531, 5631, 5831, 5931, 6031
                ],
                "4D3FB4": [
                    2101, 2201, 2301, 2701, 4301, 2102, 2202, 2302, 2702, 4302,
                    5909, 5910, 5325, 5425, 5525, 5925, 5326, 5426, 5526, 5926
                ],
                "3F3494": [
                    1605, 1705, 1805, 1905, 2005, 2405, 2605, 2805, 4205, 4405,
                    5805, 5905, 6005, 1606, 1706, 1806, 1906, 2006, 2106, 2206,
                    2306, 2406, 2606, 2706, 2806, 4206, 4306, 4406, 5806, 6006,
                    2013, 2113, 2213, 2313, 2413, 2613, 2713, 2813, 4213, 4313,
                    4413, 5813, 6013, 2014, 2414, 2614, 2814, 4214, 4414, 5814,
                    5914, 6014, 4821, 4921, 5021, 5121, 5221, 5321, 5421, 5521,
                    5621, 5821, 5921, 6021, 4822, 4922, 5022, 5122, 5222, 5622,
                    5822, 6022, 1628, 1728, 1828, 1928, 1629, 1729, 1829, 1929,
                    5229, 5629, 5829, 6029, 1630, 1730, 1830, 1930, 5230, 5330,
                    5430, 5530, 5630, 5830, 5930, 6030, 1631, 1731, 1831, 1931,
                    1632, 1732, 1832, 1932, 1633, 1733, 1833, 1933, 1634, 1734,
                    1834, 1934, 1635, 1735, 1835, 1935
                ],
                "20150F": [
                    3116, 3117, 3118, 3119, 3120, 3127, 3128, 3129, 3130, 3131,
                    3132, 3139
                ],
                "2B1B13": [3121, 3126, 3133, 3138],
                "CCCCCC": [3123],
                "B8B8B8": [3124],
                "3B251C": [3135, 3136]
            }
        }
    }
}

=== StoryAnvil/SkinEditor/src/accessories/cool_glasses.json
{
    "$schema": "../schema/stAccessory.json",
    "meta": {
        "name": "Cool Glasses",
        "author": "BloodRain121",
        "category": "face",
        "tags": []
    },
    "inputs": {
        "left": {
            "type": "color",
            "default": "FE0028",
            "name": "Left Lens",
            "alpha": 150
        },
        "right": {
            "type": "color",
            "default": "0081FE",
            "name": "Right Lens",
            "alpha": 150
        },
        "height": {
            "type": "intrange",
            "name": "Eye Height",
            "minimum": -3,
            "maximum": 1,
            "default": -1
        }
    },
    "actions": [
        {
            "type": "addoffset",
            "layers": ["l0"],
            "y_offset": {
                "type": "input",
                "input": "height"
            }
        }
    ],
    "layers": {
        "l0": {
            "buffer": "b0",
            "enabledByDefault": true
        }
    },
    "buffers": {
        "b0": {
            "px": {
                "303030": [
                    1335, 1238, 1339, 1340, 1241, 1344, 1246, 1347, 1348, 1249,
                    1352
                ],
                "3E3E3E": [1236, 1237, 1242, 1243, 1244, 1245, 1250, 1251],
                "1F1F1F": [1239, 1240, 1343, 1247, 1248],
                "#left": [1341, 1342],
                "#right": [1345, 1346]
            }
        }
    }
}

=== StoryAnvil/SkinEditor/src/accessories/cat.json
{
    "$schema": "../schema/stAccessory.json",
    "meta": {
        "name": "Cat",
        "author": "",
        "category": "face",
        "tags": []
    },
    "inputs": {
        "c0": {
            "type": "color",
            "name": "Outside color",
            "default": "FFFFFF"
        },
        "c1": {
            "type": "color",
            "name": "Inside color",
            "default": "F6C7D4"
        }
    },
    "layers": {
        "l0": {
            "buffer": "b0",
            "enabledByDefault": true
        }
    },
    "buffers": {
        "b0": {
            "px": {
                "#c0": [
                    708, 709, 714, 715, 807, 808, 809, 814, 815, 816, 907, 908,
                    910, 913, 915, 916, 1007, 1008, 1015, 1016, 741, 746, 841,
                    846, 939, 940, 942, 945, 947, 948, 1039, 1040, 1047, 1048
                ],
                "#c1": [909, 914, 1009, 1014, 1041, 1046],
                "00000000": [941, 946]
            }
        }
    }
}
